### ISSUE TITLE
Error using the proj_inv

### ISSUE THREAD

**Issue by mali-rcx** [nguyennico/planr#9]
Hi - whenever I try to use the proj_inv function of your package it gives me the following error, I have tried with my own dataset and with the dataset you created on R views. I have also attached the file I am currently using to practice it. The error message is as follows: 

Joining with `by = join_by(DFU, Period)`
Error in `mutate()`:
ℹ In argument: `Safety.Stocks = case_when(...)`.
ℹ In group 1: `DFU = "Product A"`.
Caused by error:
! `Safety.Stocks` must be size 7 or 1, not 0.
Run `rlang::last_trace()` to see where the error occurred.

[Forecast Practice.csv](https://github.com/nguyennico/planr/files/12728666/Forecast.Practice.csv)

**Comment by nguyennico** [comment]
Hello,

I had a look at the file, do you think you could try again :
- renaming the minium & maximum stocks as Min.Cov and Max.Cov ?
- formatting the Period as a date ?

Then applying :

df1 <- proj_inv(data = Forecast_Practice,
                DFU = DFU,
                Period = Period,
                Demand =  Demand,
                Opening = Opening,
                Supply = Supply,
                Min.Cov = Min.Cov,
                Max.Cov = Max.Cov)

I just gave it a try and got the results below.

Please let me know how it goes.

Thank you,
Cheers,
Nico



[image: image.png]

**Comment by mali-rcx** [comment]
Hi again -

Thank you for your response, I was able to make it work after applying your suggestions. I am currently working on using your package to forecast inventory for real products, will update how it goes. This is an amazing package, thank you for developing it !!

**Comment by nguyennico** [comment]
Hello !
Great ! I'm glad to hear this !:)
Yes, please keep me updated on your work with the package .
Thank you,
Cheers,
Nico
